name: env in container name

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ${{ vars.IMAGE }}:${{ vars.IMAGE_TAG }}
    steps:
      - name: env
        run: echo hello
